#pragma once


#define RD_MOUSE_BUTTON_1         0
#define RD_MOUSE_BUTTON_2         1
#define RD_MOUSE_BUTTON_3         2
#define RD_MOUSE_BUTTON_4         3
#define RD_MOUSE_BUTTON_5         4
#define RD_MOUSE_BUTTON_6         5
#define RD_MOUSE_BUTTON_7         6
#define RD_MOUSE_BUTTON_8         7
#define RD_MOUSE_BUTTON_LAST      RADIANT_MOUSE_BUTTON_8
#define RD_MOUSE_BUTTON_LEFT      RADIANT_MOUSE_BUTTON_1
#define RD_MOUSE_BUTTON_RIGHT     RADIANT_MOUSE_BUTTON_2
#define RD_MOUSE_BUTTON_MIDDLE    RADIANT_MOUSE_BUTTON_3